default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: my_blog2_development
  pool: 5
  username: postgres
  password: 12345

test:
  adapter: postgresql
  encoding: unicode
  database: my_blog2_test
  pool: 5
  username: postgres
  password: 12345

production:
  <<: *default
  database: my_blog2_production
  username: postgres
  password: <%= ENV["RAILS_BLOG_APP_DATABASE_PASSWORD"] %>